// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FontInfo {
    /**
     * Creates a new FontInfo instance.
     * @param {Partial<FontInfo>} [$$source = {}] - The source object to create the FontInfo.
     */
    constructor($$source = {}) {
        if (!("family" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["family"] = "";
        }
        if (!("weight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["weight"] = 0;
        }
        if (!("italic" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["italic"] = false;
        }
        if (!("stretch" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stretch"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FontInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FontInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FontInfo(/** @type {Partial<FontInfo>} */($$parsedSource));
    }
}

export class Note {
    /**
     * Creates a new Note instance.
     * @param {Partial<Note>} [$$source = {}] - The source object to create the Note.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("winX" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["winX"] = 0;
        }
        if (!("winY" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["winY"] = 0;
        }
        if (!("winWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["winWidth"] = 0;
        }
        if (!("winHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["winHeight"] = 0;
        }
        if (!("isOpen" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isOpen"] = false;
        }
        if (!("alwaysOnTop" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysOnTop"] = false;
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created"] = "";
        }
        if (!("updated" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Note}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Note(/** @type {Partial<Note>} */($$parsedSource));
    }
}

export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("startupEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["startupEnabled"] = false;
        }
        if (!("fontFamily" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fontFamily"] = "";
        }
        if (!("fontSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fontSize"] = 0;
        }
        if (!("fontWeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fontWeight"] = 0;
        }
        if (!("fontItalic" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["fontItalic"] = false;
        }
        if (!("fontStretch" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fontStretch"] = 0;
        }
        if (!("lineHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lineHeight"] = 0;
        }
        if (!("letterSpacing" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["letterSpacing"] = 0;
        }
        if (!("imgWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["imgWidth"] = 0;
        }
        if (!("mainWinX" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mainWinX"] = 0;
        }
        if (!("mainWinY" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mainWinY"] = 0;
        }
        if (!("mainWinWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mainWinWidth"] = 0;
        }
        if (!("mainWinHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mainWinHeight"] = 0;
        }
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("confirmDelete" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirmDelete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}
