// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as http$0 from "../net/http/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function CloseNote(id) {
    return $Call.ByID(4050224191, id);
}

/**
 * @returns {$CancellablePromise<$models.Note>}
 */
export function CreateNote() {
    return $Call.ByID(3901296041).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNote(id) {
    return $Call.ByID(3639942098, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Note>}
 */
export function GetNoteById(id) {
    return $Call.ByID(2700050483, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Note[]>}
 */
export function GetNotes() {
    return $Call.ByID(4001444448).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(2084625886).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetStartupEnabled() {
    return $Call.ByID(2272562437);
}

/**
 * @returns {$CancellablePromise<$models.FontInfo[]>}
 */
export function GetSystemFonts() {
    return $Call.ByID(1021707112).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {http$0.Handler} next
 * @returns {$CancellablePromise<http$0.Handler>}
 */
export function ImageMiddleware(next) {
    return $Call.ByID(116186174, next);
}

/**
 * @param {string} noteId
 * @param {string} src
 * @returns {$CancellablePromise<void>}
 */
export function OpenImageViewer(noteId, src) {
    return $Call.ByID(1977489720, noteId, src);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenMainWindow() {
    return $Call.ByID(1563872924);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function OpenNoteWindow(id) {
    return $Call.ByID(3053419677, id);
}

/**
 * @param {string} noteId
 * @param {string} data
 * @param {string} filename
 * @returns {$CancellablePromise<string>}
 */
export function SaveImage(noteId, data, filename) {
    return $Call.ByID(703632737, noteId, data, filename);
}

/**
 * @param {$models.Note} note
 * @returns {$CancellablePromise<void>}
 */
export function SaveNoteNow(note) {
    return $Call.ByID(2161968472, note);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetStartupEnabled(enabled) {
    return $Call.ByID(2190687449, enabled);
}

/**
 * @param {$models.Note} note
 * @returns {$CancellablePromise<$models.Note>}
 */
export function UpdateColor(note) {
    return $Call.ByID(1141830583, note).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.Note} note
 * @returns {$CancellablePromise<$models.Note>}
 */
export function UpdateNote(note) {
    return $Call.ByID(163960476, note).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.Note} note
 * @returns {$CancellablePromise<$models.Note>}
 */
export function UpdatePin(note) {
    return $Call.ByID(1781239663, note).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.Settings} settings
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSettings(settings) {
    return $Call.ByID(1016301389, settings);
}

// Private type creation functions
const $$createType0 = $models.Note.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Settings.createFrom;
const $$createType3 = $models.FontInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
